(function(){(function(){function d(a,b){this.element=a;"[object Object]"===Object.prototype.toString.call(b)?this.options=b:this.options={};this.init();this.gotoslide(0);this.autoplay&&this.play()}var g,e,h,k,f,c;d.prototype.pause=function(){clearTimeout(this.interval)};d.prototype.play=function(){clearTimeout(this.interval);this.interval=setTimeout(g,this.duration,this)};d.prototype.next=function(){this.gotoslide(this.currentIndex<this.slides.length-1?this.currentIndex+1:0)};d.prototype.gotoslide=
function(a){var b;this.currentIndex!==a&&((b=this.element.parentNode.querySelector(".visible"))&&b===this.slideA?(this.slideB.style.backgroundPosition="0px "+String(-1*this.options.height*a)+"px",this.slideA.className=this.slideA.className.replace(/(\s|^)visible(\s|$)/,""),this.slideB.className+=" visible"):(this.slideA.style.backgroundPosition="0px "+String(-1*this.options.height*a)+"px",this.slideB.className=this.slideB.className.replace(/(\s|^)visible(\s|$)/,""),this.slideA.className+=" visible"),
(b=this.navigation.querySelector(".active"))&&b.removeAttribute("class"),b=document.createAttribute("class"),b.nodeValue="active",this.navigation.childNodes.item(a).setAttributeNode(b),b=-1===this.currentIndex?0:this.currentIndex,this.slides[b].el.className=this.slides[b].el.className.replace(/(\s|^)active(\s|$)/,""),this.slides[a].el.className+=" active",this.currentIndex=a)};d.prototype.init=function(){var a,b,l,d,g;b=this;this.options.width||(this.options.width=this.element.offsetWidth);this.options.height||
(this.options.height=this.element.offsetHeight);this.autoplay=!0;this.duration=5E3;this.currentIndex=-1;this.element.className.match(/(\s|^)fss(\s|$)/)||(this.element.className+=" fss");if(this.caption=this.element.querySelector(".captions")){a=this.caption.firstChild;d=0;for(this.slides=[];a;)a&&3!==a.nodeType&&this.slides.push({ndx:d++,el:a}),a=a.nextSibling;this.container=e("div","slide-container");this.slideA=e("div","slide-a visible");this.slideB=e("div","slide-b");this.element.insertBefore(this.container,
this.caption);this.container.appendChild(this.slideA);this.container.appendChild(this.slideB);this.slideA.style.width=this.slideB.style.width=this.options.width+"px";this.slideA.style.height=this.slideB.style.height=this.options.height+"px";this.navigation=e("ul","fss-nav");l=this.slides;a=d=0;for(g=l.length;d<g;a=++d)l=e("li"),l.appendChild(document.createTextNode(String(a+1))),this.navigation.appendChild(l),l.onclick=c(l,this);this.container.appendChild(this.navigation);this.container.onmouseover=
function(a){return f(a,b)};this.container.onmouseout=function(a){return k(a,b)}}};e=function(a,b){var c,f;f=document.createElement(a);if(!b)return f;c=document.createAttribute("class");c.nodeValue=b;f.setAttributeNode(c);return f};h=function(a,b){if(a===b)return!1;for(;a&&a!==b;)a=a.parentNode;return a===b};g=function(a){a&&(a.next(),a.play())};c=function(a,b){return function(){var c;b.pause();for(c=0;b.navigation.childNodes.item(c);){if(b.navigation.childNodes.item(c)===a){b.gotoslide(c);break}c++}}};
f=function(a,b){if(a){if(!h(a.target,b.container))return a.cancelBubble=!0,a.stopPropagation(),!1;b.pause();b.navigation.className.match(/(\s|^)active(\s|$)/)||(b.navigation.className+=" active")}};k=function(a,b){if(h(a.relatedTarget,b.container))return a.cancelBubble=!0,a.stopPropagation(),!1;b.play();b.navigation.className.match(/(\s|^)active(\s|$)/)&&(b.navigation.className=b.navigation.className.replace(/(\s|^)active(\s|$)/,""))};return d})()}).call(this);
(function(){(function(){function d(f,c){this.element=f;"[object Object]"===Object.prototype.toString.call(c)?this.options=c:this.options={};this.options.resizeImage=!1;this.init()}var g,e,h,k;d.prototype.init=function(){var f;f=this;this.element.onclick=function(c){return g(c,f)}};d.prototype.createOverlay=function(f){var c;c=this;this.overlay=document.createElement("div");this.overlay.setAttribute("id","flb-overlay");this.overlay.innerHTML='<div id="flb-container"><a href="#" title="Close" class="closingElement">&nbsp;</a></div><div id="flb-content"><a id="flb-image" class="closingElement" href="#" title="Close"></a><a id="flb-close" class="closingElement" href="#" title="Close">&times;</a></div>';
document.getElementsByTagName("body")[0].appendChild(this.overlay);this.container=document.getElementById("flb-content");this.container.onclick=this.overlay.onclick=function(a){return e(a,c)};this.imgContainer=document.getElementById("flb-image");this.imgContainer.style.background="url("+f+") no-repeat 50% 50%";this.image=new Image;this.image.onload=function(a){return h(a,c)};this.image.src=f};h=function(f,c){var a,b,d;c.options.resizeImage?(d=document.documentElement.clientHeight-40,c.image.height<
d?(a=c.image.height,b=c.image.width):(a=d,b=Math.round(d*c.image.width/c.image.height),c.image.height=a,c.image.width=b)):(a=c.image.height,b=c.image.width);setTimeout(function(){return k(c.container,b,a)},600)};k=function(f,c,a){f.style.width=c+"px";f.style.height=a+"px";f.style.margin="-"+(a+28)/2+"px 0 0 -"+c/2+"px";f.setAttribute("class","active")};g=function(f,c){c.createOverlay(f.currentTarget.getAttribute("href"));f.cancelBubble=!0;f.stopPropagation();return!1};e=function(f,c){c.container.setAttribute("class",
"");document.getElementsByTagName("body")[0].removeChild(c.overlay)};return d})()}).call(this);
(function(){window.onload=function(){var d,g,e,h,k;if(document.querySelector){g=document.querySelectorAll("#hero_slideshow .slideshow");if(g.length){e=0;for(h=g.length;e<h;e++)d=g[e],new FSS(d,{width:725,height:210})}g=document.querySelectorAll("a[rel=simplebox]");if(g.length){e=0;for(h=g.length;e<h;e++)d=g[e],new FLB(d,{})}d=function(f,c){return function(){var a,b,d,e,g;a=f.getAttribute("rel");d=0;for(e=c.length;d<e;d++)b=c[d],b.className.match(/(\s|^)active(\s|$)/)&&(b.className=b.className.replace(/(\s|^)active(\s|$)/,
""));d=document.querySelectorAll("#projects_list li");e=0;for(g=d.length;e<g;e++)b=d[e],b.className.match(/(\s|^)deselected(\s|$)/)&&(b.className=b.className.replace(/(\s|^)deselected(\s|$)/,"")),"all"!==a&&!b.className.match(RegExp("(\\s|^)"+a+"(\\s|$)"))&&!b.className.match(/(\s|^)deselected(\s|$)/)&&(b.className+=" deselected");f.className=" active"}};if(document.querySelector("#p72")){e=document.querySelectorAll("#projects-nav dd");h=0;for(k=e.length;h<k;h++)g=e[h],g.onclick=d(g,e)}if(d=document.querySelector("#post-tweet"))return d.onclick=
function(){var d,c;d=window.screen.width/2-275;c=window.screen.height/2-235;window.open(this.href,this.getAttribute("target"),"width=550, height=470, location=0, left="+d+", top="+c);return!1}}}}).call(this);
